apiVersion: apps/v1
kind: Deployment
metadata:
  name: saaspe-microservice
  # namespace: dev
  labels:
    app: saaspe-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saaspe-microservice
  template:
    metadata:
      name: saaspe-microservice
      labels:
        app: saaspe-microservice
    spec:
      priorityClassName: mid-priority-pod
      containers:
        - name: saaspe-microservice
          image: saaspe.azurecr.io/saaspeapi:${{ image_tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              port: 6060
              path: /actuator/health/liveness
            initialDelaySeconds: 120
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 15 
          readinessProbe:
            httpGet:
              port: 6060
              path: /actuator/health/readiness
            initialDelaySeconds: 180
            initialDelaySeconds: 180
            periodSeconds: 120
          resources:
            requests:
              memory: "4Gi"
              cpu: "700m"
            limits:
              memory: "4Gi"
              cpu: "700m"
          env:
           - name: SPRING_DATASOURCE_URL       
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: POSTGRES_URL        
           - name: SPRING_DATASOURCE_USERNAME    
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: POSTGRES_USERNAME
           - name: SPRING_DATASOURCE_PASSWORD    
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: POSTGRES_PASSWORD
           - name: SPRING_DATA_MONGODB_CLOUD_HOST    
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_CLOUD_HOST
           - name: SPRING_DATA_MONGODB_CLOUD_USERNAME   
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_CLOUD_USERNAME
           - name: SPRING_DATA_MONGODB_CLOUD_PASSWORD   
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_CLOUD_PASSWORD
           - name: SPRING_DATA_MONGODB_CLOUD_DATABASE  
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_CLOUD_DATABASE                                 
           - name: SPRING_DATA_MONGODB_MARKETPLACE_HOST  
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_MARKETPLACE_HOST
           - name: SPRING_DATA_MONGODB_MARKETPLACE_USERNAME
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_MARKETPLACE_USERNAME
           - name: SPRING_DATA_MONGODB_MARKETPLACE_PASSWORD
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_MARKETPLACE_PASSWORD
           - name: SPRING_DATA_MONGODB_MARKETPLACE_DATABASE
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_MARKETPLACE_DATABASE
           - name: CURRENCY_DATASOURCE_URL
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: CURRENCY_URL  
           - name: CURRENCY_DATASOURCE_USERNAME
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: CURRENCY_USERNAME
           - name: CURRENCY_DATASOURCE_PASSWORD
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: CURRENCY_PASSWORD                                   
           - name: SPRING_DATA_MONGODB_DOCUSIGN_HOST
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_DOCUSIGN_HOST
           - name: SPRING_DATA_MONGODB_DOCUSIGN_USERNAME
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_DOCUSIGN_USERNAME
           - name: SPRING_DATA_MONGODB_DOCUSIGN_PASSWORD
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_DOCUSIGN_PASSWORD
           - name: SPRING_DATA_MONGODB_DOCUSIGN_DATABASE
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: MONGODB_DOCUSIGN_DATABASE
           - name: ADAPTERS_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: ADAPTERS_HOST_URL
           - name: AWS_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: AWS_HOST_URL
           - name: AZURE_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: AZURE_HOST_URL
           - name: CURRENCY_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: CURRENCY_HOST_URL
           - name: CLM_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: CLM_HOST_URL
           - name: DOCUSIGN_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: DOCUSIGN_HOST_URL
           - name: AI_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: AI_HOST_URL
           - name: STRIPE_HOST_URL
             valueFrom:
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: STRIPE_HOST_URL
           - name: SPRING_MAIL_HOST
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: SPRING_MAIL_HOST
           - name: SPRING_MAIL_PORT
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: SPRING_MAIL_PORT
           - name: SPRING_MAIL_USERNAME
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: SPRING_MAIL_USERNAME
           - name: SPRING_MAIL_PASSWORD
             valueFrom: 
               configMapKeyRef:
                 name: saaspe-microservices-config
                 key: SPRING_MAIL_PASSWORD
